
// Objective-C API for talking to the following Go packages
//
//	gitlab.com/jack4redpay/gomobile4wallet
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Gomobile4wallet_FRAMEWORK_H__
#define __Gomobile4wallet_FRAMEWORK_H__

#include "Gomobile4wallet.objc.h"
#include "Universe.objc.h"

#endif
