// Objective-C API for talking to gitlab.com/jack4redpay/gomobile4wallet Go package.
//   gobind -lang=objc gitlab.com/jack4redpay/gomobile4wallet
//
// File is generated by gobind. Do not edit.

#ifndef __Gomobile4wallet_H__
#define __Gomobile4wallet_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


// skipped function FnGetBalance with unsupported parameter or return types


FOUNDATION_EXPORT NSString* _Nonnull Gomobile4walletFnGetWalletAddress(NSString* _Nullable tmp, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull Gomobile4walletFnNewTransaction(NSString* _Nullable tmp2, NSString* _Nullable tmp3, NSString* _Nullable tmp4, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull Gomobile4walletFnNewWallet(NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT void Gomobile4walletGetBlock(NSString* _Nullable file);

FOUNDATION_EXPORT void Gomobile4walletGetTranss(NSString* _Nullable s);

// skipped function GetWallet with unsupported parameter or return types


FOUNDATION_EXPORT NSString* _Nonnull Gomobile4walletGetWalletAddress(NSString* _Nullable file);

// skipped function GetWalletSum with unsupported parameter or return types


FOUNDATION_EXPORT NSString* _Nonnull Gomobile4walletGreetings(NSString* _Nullable name);

// skipped function NewTrans with unsupported parameter or return types


// skipped function NewWallet with unsupported parameter or return types


FOUNDATION_EXPORT BOOL Gomobile4walletNumberError(long num, long* _Nullable ret0_, NSError* _Nullable* _Nullable error);

// skipped function PutTrans with unsupported parameter or return types


FOUNDATION_EXPORT NSString* _Nonnull Gomobile4walletReverse(NSString* _Nullable a);

#endif
